name: refresh-lightdash

on:
  push:
    branches: [ "main", "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3.4.1

      - name: Get lightdash version
        uses: sergeysova/jq-action@v2
        id: version
        env:
          LIGHTDASH_URL: ${{ secrets.LIGHTDASH_URL }}
        with:
          cmd: curl -s "${LIGHTDASH_URL}/api/v1/health" | jq -r '.results.version'

      - name: Install lightdash CLI
        run: npm install -g "@lightdash/cli@${{ steps.version.outputs.value }}" || npm install -g @lightdash/cli@latest

      - name: Lightdash CLI deploy
        env:
          LIGHTDASH_API_KEY: ${{ secrets.LIGHTDASH_API_KEY }}
          LIGHTDASH_PROJECT: ${{ secrets.LIGHTDASH_PROJECT }}
          LIGHTDASH_URL: ${{ secrets.LIGHTDASH_URL }}
        run: lightdash refresh
